In [1]:
import psycopg2
import pandas as pd
import dotenv
import os

In [2]:
dotenv.load_dotenv()

True

In [3]:
mart_tables = [
'mart_nyc_hourly_patterns',
'mart_london_daily_metrics',
'mart_daily_metrics_long', 
'mart_london_station_growth',
'mart_nyc_member_analysis',
'mart_nyc_station_growth',
'mart_london_hourly_patterns',
'mart_nyc_daily_metrics'
]

In [4]:
schema = 'dbt_models_marts'

In [5]:
conn = psycopg2.connect(
    dbname=os.environ['DB_NAME'],
    user=os.environ['DB_USER'],
    password=os.environ['DB_PASSWORD'],
    host=os.environ['DB_HOST'],
    port=os.environ['DB_PORT']
)

for table in mart_tables:
    print(f"Querying table: {table}")
    query = f"SELECT * FROM {schema}.{table}"  # example mart
    print(f"Query: {query}")
    df = pd.read_sql(query, conn)
    print("Table returned as pandas df.")
    df.to_parquet(f"{table}.parquet", engine="pyarrow", index=False)
    print(f"Pandas df saved as parquet to: ~/data/{table}.parquet")
    print("\n")

Querying table: mart_nyc_hourly_patterns
Query: SELECT * FROM dbt_models_marts.mart_nyc_hourly_patterns
Table returned as pandas df.

/var/folders/4n/x45lx83x6b9c1n8215hh7rkh0000gn/T/ipykernel_18071/777305383.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

Pandas df saved as parquet to: ~/data/mart_nyc_hourly_patterns.parquet


Querying table: mart_london_daily_metrics
Query: SELECT * FROM dbt_models_marts.mart_london_daily_metrics
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_london_daily_metrics.parquet


Querying table: mart_daily_metrics_long
Query: SELECT * FROM dbt_models_marts.mart_daily_metrics_long
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_daily_metrics_long.parquet


Querying table: mart_london_station_growth
Query: SELECT * FROM dbt_models_marts.mart_london_station_growth
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_london_station_growth.parquet


Querying table: mart_nyc_member_analysis
Query: SELECT * FROM dbt_models_marts.mart_nyc_member_analysis
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_nyc_member_analysis.parquet


Querying table: mart_nyc_station_growth
Query: SELECT * FROM dbt_models_marts.mart_nyc_station_growth
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_nyc_station_growth.parquet


Querying table: mart_london_hourly_patterns
Query: SELECT * FROM dbt_models_marts.mart_london_hourly_patterns
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_london_hourly_patterns.parquet


Querying table: mart_nyc_daily_metrics
Query: SELECT * FROM dbt_models_marts.mart_nyc_daily_metrics
Table returned as pandas df.
Pandas df saved as parquet to: ~/data/mart_nyc_daily_metrics.parquet

## Now, let's confirm that worked.

In [6]:
## Test reading from one of the parquet files!
test_df = pd.read_parquet("mart_daily_metrics_long.parquet")

In [7]:
test_df.head()

        date location    year           metric_name  metric_value
0 2019-01-01      nyc  2019.0  avg_duration_minutes  1.960705e+01
1 2019-01-01      nyc  2019.0          casual_rides  4.665000e+03
2 2019-01-01      nyc  2019.0          member_rides  1.729700e+04
3 2019-01-01      nyc  2019.0            population  8.336817e+06
4 2019-01-01      nyc  2019.0        rides_per_1000  2.634339e+00

In [8]:
len(test_df)

26332

In [9]:
test_query = "SELECT count(*) as row_count FROM dbt_models_marts.mart_daily_metrics_long"

In [10]:
test_query_df = pd.read_sql(test_query, conn)

/var/folders/4n/x45lx83x6b9c1n8215hh7rkh0000gn/T/ipykernel_18071/4042016754.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  test_query_df = pd.read_sql(test_query, conn)

In [11]:
test_query_df.head(1)

   row_count
0      26332

### Looking good!